### ISSUE TITLE
No "gfx/numbers_gfx.h"

### ISSUE THREAD

**Issue by SConaway** [Ricovl/CE2048#1]

**Comment by Modd3d** [comment]
@Ricovl +1 
the .gitignore is the cause.
`src/gfx/*.c
src/gfx/*.h`

**Comment by Ricovl** [comment]
You have to run convimg in order to generate the missing numbers_gfx.h file. This can be done by running the command `make gfx`. This wasn't working before with the new versions of the toolchain and convimg, but it should work now after my most recent commits.
